### PR TITLE
Using Durstenfeld algorithm for randomizing page order

### PR DESCRIPTION
**Pull request by krlln**
Addressing issue #33

### CODE REVIEW

**Comment by faroit** [comment]
Thanks, let me fix the travis test in the master branch first, before we merge this

**Comment by faroit** [comment]
@krlln done via #35

**Comment by krlln** [comment]
After some thoughts, I would suggest moving the `shuffle` function in another file (maybe below `lib/webmushra/misc` so that we can use it from `MushraAudioControl.js`. Hence removing the, now infamous, `0.5 - Math.random()` that's still present in this file.

**Comment by faroit** [comment]
okay, that sounds good. thanks

**Comment by faroit** [comment]
@mschoeffler do you have time for a review?

**Pull request merged**
