### PR TITLE
set audioMaxPosition to safe minimum length

### LINKED ISSUE #12: Support safe playback of reference and stimuli of different length
Currently when the reference and the stimuli have a different number of samples an error is thrown and if `stopOnErrors: true` is set, experiments will not be started.

If experiments are started nonetheless webMUSHRA behaves as followed:
* the size of the output buffer is determined by the length of the reference
* when the reference is __shorter__ than then a stimulus, the stimuli will be trimmed to the length of the reference. this does not affect playback.
* when the reference is __longer__ than a stimulus, the buffer might be filled up with undefined memory content, resulting in weird output on some browsers.

The expected behaviour in this case would be that the stimuli are filled up/padded with silence. Even though we decided earlier to force users to make sure that references and stimuli have the same length;  user feedback shows that this fix would increase the usability for many users.

### PR DESCRIPTION
**Pull request by faroit**
this would fix #12 in case someone wants to playback a stimuli that is __shorter__ than the reference, even though an error is thrown.

### CODE REVIEW

**Comment by mschoeffler** [comment]
I suggest to wait for a few more days/weeks if another solution pops up. As Alex wrote, this fix does alter the reference in some cases. In my opinion, we should aim at a solution that does trimming as well as padding if required.

**Comment by faroit** [comment]
Any update on this?

**Comment by faroit** [comment]
@mschoeffler can we merge this?

**Comment by aladami** [comment]
Are there any new opinions/updates on this issue? If not, I recommend a merge to have at least a basic fix that provides a defined behavior.

**Pull request merged**
