### PR TITLE
Support Docker

### PR DESCRIPTION
**Pull request by faroit**
This adds docker configuration files. Using docker users can setup webMUSHRA within seconds without any further webserver configuration on Mac, Windows and Linux.

Please test on windows

### CODE REVIEW

**Comment by aladami** [comment]
For windows, the statement `$env:COMPOSE_CONVERT_WINDOWS_PATHS=1` has to be added  to account for windows path names.

Since also additionally steps are necessary to make it work on windows (Win7+ Docker Toolbox) than simply executing the stated command lines, this should be mentioned explicitly by means of a step-by-step explaination in the documentation.

**Comment by faroit** [comment]
I think that it's not our job to document how to use docker. Maybe we just add a that Docker for Windows requires Windows 10 Pro?

**Comment by aladami** [comment]
> I think that it's not our job to document how to use docker. 

You may be right, but isn't one the reasons for providing a docker configuation to make the setup of webMushra easier for people who are not so proficient with all the tools? I am sure, people will appreciate it. 
Besides that it may also incease the number of users, when you do not have to spend hours to find out how to get things to work.

> Maybe we just add a that Docker for Windows requires Windows 10 Pro

This would be possible, provided that there are not the same issues. I did/could not test that.

**Comment by faroit** [comment]
okay, I've added a `Docker on Windows` note to the readme

**Pull request merged**
